// Shared constants used across web + exports.

import type { City, FinishTier, RoomType, StateCode } from "./plan";

// Legal framing strings — must appear in UI and on every export.
export const DISCLAIMERS = {
  vastu: "Vastu-informed guidance (not certification).",
  code: "Preliminary code review — verify with a registered architect before submission.",
  export: "Generated by GharPlan. Indicative only. Not an approved/stamped drawing.",
} as const;

export const CITIES: City[] = ["Bengaluru", "Hyderabad", "Pune"];

export const STATE_BY_CITY: Record<City, StateCode> = {
  Bengaluru: "KA",
  Hyderabad: "TG",
  Pune: "MH",
};

export const FINISH_TIERS: FinishTier[] = ["economy", "standard", "premium"];

export const ROOM_TYPES: RoomType[] = [
  "pooja",
  "kitchen",
  "master_bedroom",
  "bedroom",
  "childrens_bedroom",
  "living",
  "dining",
  "toilet",
  "bathroom",
  "staircase",
  "entrance",
  "study",
  "store",
  "utility",
  "balcony",
  "parking",
  "overhead_tank",
  "borewell",
  "brahmasthan",
];

export const ROOM_LABELS: Record<RoomType, string> = {
  pooja: "Pooja",
  kitchen: "Kitchen",
  master_bedroom: "Master Bedroom",
  bedroom: "Bedroom",
  childrens_bedroom: "Children's Bedroom",
  living: "Living",
  dining: "Dining",
  toilet: "Toilet",
  bathroom: "Bathroom",
  staircase: "Staircase",
  entrance: "Entrance",
  study: "Study",
  store: "Store",
  utility: "Utility",
  balcony: "Balcony",
  parking: "Parking",
  overhead_tank: "Overhead Tank",
  borewell: "Borewell",
  brahmasthan: "Brahmasthan",
};

// Billing (M4). Amounts in INR. TODO(human): confirm final pricing + Razorpay plan IDs.
export const BILLING = {
  creditPriceInr: 499, // 1 export-ready plan
  plans: [
    { id: "solo_5", label: "Studio (5 plans/mo)", priceInr: 1500, planCredits: 5 },
    { id: "solo_unlimited", label: "Solo Unlimited", priceInr: 2999, planCredits: null },
  ],
} as const;
