"""Runtime configuration and fixture path resolution.

The engine reads its domain data (Vastu rules, code rules, BOQ rules, rate seed)
from the repo-level ``/fixtures`` directory so the web app and engine share one
source of truth. Paths can be overridden with ``GHARPLAN_FIXTURES_DIR``.
"""

from __future__ import annotations

import os
from pathlib import Path

APP_DIR = Path(__file__).resolve().parent          # .../engine/app
ENGINE_DIR = APP_DIR.parent                         # .../engine
REPO_ROOT = ENGINE_DIR.parent                       # repo root

FIXTURES_DIR = Path(os.getenv("GHARPLAN_FIXTURES_DIR", str(REPO_ROOT / "fixtures")))

# Domain data files
BOQ_RULES_PATH = FIXTURES_DIR / "boq_rules.json"
RATES_SEED_PATH = FIXTURES_DIR / "rates" / "rates_seed.json"
VASTU_RULES_PATH = FIXTURES_DIR / "vastu_rules.json"
CODE_RULES_PATH = FIXTURES_DIR / "code_rules.json"
TEMPLATES_DIR = FIXTURES_DIR / "templates"

# Brahmasthan (CENTER) detection: "grid_3x3" (classical central 1/9) or "area_rect_10pct".
# TODO(human): confirm preferred strategy with a practising Vastu consultant.
BRAHMASTHAN_STRATEGY = os.getenv("GHARPLAN_BRAHMASTHAN", "grid_3x3")

# Feature flags
# The deterministic floor-plan generator is GA and ON by default; the flag is
# retained only as a kill switch (set FEATURE_GENERATOR=false to disable).
FEATURE_GENERATOR = os.getenv("FEATURE_GENERATOR", "true").lower() in {"1", "true", "yes"}

# CORS
CORS_ORIGINS = [
    o.strip() for o in os.getenv(
        "ENGINE_CORS_ORIGINS",
        "http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:3003"
    ).split(",") if o.strip()
]

# Legal framing strings — reused in UI copy and every export.
DISCLAIMER_EXPORT = "Generated by Vastukala AI. Indicative only. Not an approved/stamped drawing."
DISCLAIMER_VASTU = "Vastu-informed guidance (not certification)."
DISCLAIMER_CODE = "Preliminary code review — verify with a registered architect before submission."
